### PR TITLE
feat(query): UTxO RPC Provider for Blaze

### PR DESCRIPTION
**Pull request by Mercurial**
This PR implements a minimal viable UTxORPC provider for Blaze

The following functions are implemented

- `getParameters`
- `getUnspentOutputs`
- `getUnspentOutputsWithAsset`
- `getUnspentOutputByNFT`
- `resolveUnspentOutputs`
- `postTransactionToChain`

### CODE REVIEW

**Review by rvcas — APPROVED** [review]

**Comment by ilap** [comment]
Hey @micahkendall and @Mercurial,

I don’t think this change worked out well—it’s really messed up browser compatibility. 
Can we chat about other options to fix this?

Thanks!

**Comment by Mercurial** [comment]
Oh what about it? Is it related to the grpc client?

**Comment by ilap** [comment]
> Oh what about it? Is it related to the grpc client?

The @utxorpc/sdk is a Node sdk that mainly uses the "@connectrpc/connect-node" that is not browser compatible. Though, connectrpc has a (non-public) browser friendly package. I am not sure that it could be polyfill-ed at all.

**Comment by Mercurial** [comment]
yep I suspected that and that makes sense, will make the necessary changes. Probably best to publish two versions node and browser sdk

**Comment by ilap** [comment]
Thx @Mercurial,
Anyway, would you mind to bump @blaze-cardano/ogmios to `v0.0.6` (as it was not with the latest merged PRs) and the kupmios package to `0.2.16`, with that updated dependency  (`0.0.6`) in its package.json?

**Pull request merged**
